name: CI Pipeline
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build-test-docker:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
 
    - name: Run Tests
      run: pytest
 
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
 
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sample-ci-cd-app:latest .
 
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sample-ci-cd-app:latest
